apiVersion: v2
name: prometheus
description: Easily launch Prometheus via a HelmChart
type: application
version: 0.1.0-alpha.0

dependencies:
  - name: kube-prometheus-stack
    version: "81.5.1"  # pin a known-good version
    repository: "https://prometheus-community.github.io/helm-charts"
